# -*- coding: utf-8 -*-
"""Image Caption project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dF57P_NPklLKHksb3DA01lAGhBoFQQzI
"""

pip install transformers pillow torch torchvision torchaudio

from transformers import BlipProcessor, BlipForConditionalGeneration
from PIL import Image

processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-large")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-large")

image = Image.open("krishna.img")
input = processor(image, return_tensors="pt")

output = model.generate(**input)

caption = processor.decode(output[0], skip_special_tokens=True)
print(caption)